# Generated by Django 5.2.12 on 2026-03-15 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='certification.certification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_mappings', to='course.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'certification'), name='unique_course_certification_mapping')],
            },
        ),
    ]
